### PR TITLE
Added support for optimization vs other bot

### PR DESCRIPTION
**Pull request by bwnance**
In addition to allowing one to optimize vs other bots, it improves upon determining which iteration is the best, instead of determining via who wins, it determines based off the score of bot1 (the bot being optimized) - the score of bot2 (the bot being being optimized against). This allows you to optimize a bot against one that it is unable to win against.

### CODE REVIEW

**Comment by bwnance** [comment]
Also fixes the issue of redundant scoring. Much faster, now.

**Comment by ghost** [comment]
+1 what about multiple enemies at once? This way you don't optimize too heavily in one direction. :)

**Comment by bwnance** [comment]
Hm, but what if two enemies end up undoing the optimization? it should be easy enough to do, though.

**Comment by bwnance** [comment]
Also, don't pull this yet @Spferical theres a bug I have to fix, it loops infinitely at some point, it has to do with my redundant scoring fix.

**Comment by Spferical** [comment]
Nice catch on the redundant scoring. That's a huge boost.

There might be a case for reducing the matches_to_run as the score-based scoring could make results more accurate. Setting it to 100 in the first place was a bit arbitrary. It should probably just be made configurable later.

Pitting a bot against a bunch of others until it adapts to all of them sounds great. At worst, rock-paper-scissors happens.

Awesome work!

**Comment by bwnance** [comment]
Thanks! I'll change that string. I'm a bit stumped, though, there's what looks like a random bug that puts the tuner into an infinite loop of thinking the score is already checked. I'm not quite sure what its doing, as it doesn't happen often enough for me to find something that causes it. I've checked over the code numerous times but I can't see what might be wrong.
Also, you should join the IRC! irc.freenode.net #robotgame

**Pull request merged**
